name: CI/CD Laravel Docker + Deploy EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdo_mysql

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-scripts --no-progress

      - name: Setup environment
        run: cp .env.example .env

      - name: Generate Laravel key
        run: php artisan key:generate

      - name: Run tests
        run: php artisan test

  docker:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            carloshipoldev/alpesone-api:latest
            carloshipoldev/alpesone-api:${{ github.sha }}

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Add EC2 to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Sync files to EC2
        run: |
          rsync -avz --exclude='.git' --exclude='vendor' --exclude='.github' ./ ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/alpesone-api

      - name: Deploy on EC2
        run: |
          ssh ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ubuntu/alpesone-api
            docker compose down
            docker compose pull
            docker compose up -d --build
          EOF
